export const temporarySprint = [
  { englishWord: 'drink', russianWord: 'напиток' },
  { englishWord: 'pet', russianWord: 'домашнее животное' },
  { englishWord: 'company', russianWord: 'компания' },
  { englishWord: 'line', russianWord: 'линия' },
  { englishWord: 'few', russianWord: 'несколько' },
  { englishWord: 'product', russianWord: 'товар' },
  { englishWord: 'responsible', russianWord: 'ответственность' },
  { englishWord: 'sell', russianWord: 'продать' },
  { englishWord: 'strange', russianWord: 'странный' },
  { englishWord: 'they', russianWord: 'они' },
  { englishWord: 'type', russianWord: 'тип' },
  { englishWord: 'very', russianWord: 'очень' },
  { englishWord: 'ball', russianWord: 'мяч' },
  { englishWord: 'bottom', russianWord: 'дно' },
  { englishWord: 'stand', russianWord: 'стоять' },
  { englishWord: 'tongue', russianWord: 'язык' },
  { englishWord: 'tea', russianWord: 'чай' },
  { englishWord: 'test', russianWord: 'тестовое задание' },
  { englishWord: 'snake', russianWord: 'змей' },
  { englishWord: 'wait', russianWord: 'подождите' },
  { englishWord: 'total', russianWord: 'всего' },
  { englishWord: 'walk', russianWord: 'ходить' },
  { englishWord: 'watch', russianWord: 'смотреть' },
  { englishWord: 'holiday', russianWord: 'праздничный день' },
  { englishWord: 'many', russianWord: 'многие' },
  { englishWord: 'such', russianWord: 'такой' },
  { englishWord: 'town', russianWord: 'город' },
  { englishWord: 'east', russianWord: 'восток' },
  { englishWord: 'popular', russianWord: 'популярный' },
  { englishWord: 'place', russianWord: 'место' },
  { englishWord: 'tower', russianWord: 'башня' },
  { englishWord: 'because', russianWord: 'потому что' },
  { englishWord: 'flower', russianWord: 'цветок' },
  { englishWord: 'expensive', russianWord: 'дорогой' },
  { englishWord: 'garden', russianWord: 'сад' },
  { englishWord: 'mountain', russianWord: 'гора' },
  { englishWord: 'million', russianWord: 'миллион' },
  { englishWord: 'ski', russianWord: 'лыжи' },
  { englishWord: 'train', russianWord: 'поезд' },
  { englishWord: 'world', russianWord: 'мир' },
  { englishWord: 'chemistry', russianWord: 'химия' },
  { englishWord: 'exhibit', russianWord: 'экспонат' },
  { englishWord: 'lightly', russianWord: 'слегка' },
  { englishWord: 'admission', russianWord: 'прием' },
  { englishWord: 'fame', russianWord: 'слава' },
  { englishWord: 'row', russianWord: 'строка' },
  { englishWord: 'spite', russianWord: 'злоба' },
  { englishWord: 'astronomy', russianWord: 'астрономия' },
  { englishWord: 'blame', russianWord: 'вина' },
  { englishWord: 'geography', russianWord: 'география' },
  { englishWord: 'interfere', russianWord: 'вмешиваться' },
  { englishWord: 'principal', russianWord: 'принципал' },
  { englishWord: 'super', russianWord: 'супер' },
  { englishWord: 'wet', russianWord: 'мокрый' },
  { englishWord: 'despite', russianWord: 'несмотря на' },
  { englishWord: 'dinosaur', russianWord: 'динозавр' },
  { englishWord: 'forecast', russianWord: 'прогноз' },
  { englishWord: 'genius', russianWord: 'гений' },
  { englishWord: 'gentle', russianWord: 'нежный' },
  { englishWord: 'shelf', russianWord: 'полка' },
  { englishWord: 'anxiety', russianWord: 'тревога' },
  { englishWord: 'army', russianWord: 'армия' },
  { englishWord: 'fortune', russianWord: 'состояние' },
  { englishWord: 'lend', russianWord: 'давать в долг' },
  { englishWord: 'pride', russianWord: 'гордость' },
  { englishWord: 'adequate', russianWord: 'адекватный' },
  { englishWord: 'billion', russianWord: 'миллиард' },
  { englishWord: 'carve', russianWord: 'высекает' },
  { englishWord: 'consult', russianWord: 'консультации' },
  { englishWord: 'spin', russianWord: 'вращение' },
  { englishWord: 'initial', russianWord: 'первоначальный' },
  { englishWord: 'proof', russianWord: 'доказательство' },
  { englishWord: 'tiny', russianWord: 'крошечный' },
  { englishWord: 'tutor', russianWord: 'репетитор' },
  { englishWord: 'guarantee', russianWord: 'гарантия' },
  { englishWord: 'emergency', russianWord: 'чрезвычайное происшествие' },
  { englishWord: 'intense', russianWord: 'интенсивный' },
  { englishWord: 'peak', russianWord: 'пик' },
  { englishWord: 'potential', russianWord: 'потенциал' },
  { englishWord: 'quit', russianWord: 'уволиться' },
];
